=== xli103/CS548-Enterprise-Architecture-Design/xquery-samples/Fig-4-3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.org/catalog"
	xmlns:tns="http://www.example.org/catalog"
	elementFormDefault="qualified">
	<element name="catalog">
		<complexType>
			<sequence>
				<element name="content" type="tns:contentType" 
					minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="contentType">
		<sequence>
			<element name="title" type="string" />
			<element name="pubDate" type="date" />
			<element name="genre" type="tns:genreType" 
				minOccurs="0"
				maxOccurs="unbounded" />
			<element name="info">
				<complexType>
					<choice>
						<element name="film">
							<complexType>
								<sequence>
									<element name="director" type="string" 
										maxOccurs="unbounded"/>
								</sequence>
							</complexType>
						</element>
						<element name="book">
							<complexType>
								<sequence>
									<element name="author" type="string" 
										maxOccurs="unbounded"/>
								</sequence>
							</complexType>
						</element>
						<element name="radio">
							<complexType>
								<sequence>
									<element name="director" type="string" 
										maxOccurs="unbounded"/>
								</sequence>
							</complexType>
						</element>
					</choice>
				</complexType>
			</element>
		</sequence>
		<attribute name="category" type="string" use="required" />
	</complexType>


	<simpleType name="bookGenres">
		<restriction base="string">
			<enumeration value="Drama" />
			<enumeration value="Art" />
			<enumeration value="Mystery" />
			<enumeration value="History" />
		</restriction>
	</simpleType>
	<simpleType name="filmGenres">
		<restriction base="string">
			<enumeration value="Drama" />
			<enumeration value="SciFi" />
			<enumeration value="Comedy" />
		</restriction>
	</simpleType>
	<simpleType name="musicGenres">
		<restriction base="string">
			<enumeration value="Blues" />
			<enumeration value="Classical" />
			<enumeration value="Rock and Roll" />
		</restriction>
	</simpleType>
	<simpleType name="genreType">
		<union memberTypes="tns:bookGenres
							tns:filmGenres
							tns:musicGenres" />
	</simpleType>

</schema>

=== xli103/CS548-Enterprise-Architecture-Design/xquery-samples/Fig-4-11.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:catalog xmlns:c="http://www.example.org/catalog"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/catalog Fig-4-3.xsd">

	<c:content category="Faction">
		<c:title>Lawrence of Arabia</c:title>
		<c:pubDate>1963-01-30</c:pubDate>
		<c:genre>Drama</c:genre>
		<c:genre>History</c:genre>
		<c:info>
			<c:film>
				<c:director>David Lean</c:director>
			</c:film>
		</c:info>
	</c:content>
	<c:content category="Non-Fiction">
		<c:title>Jansonâ€™s History of Art</c:title>
		<c:pubDate>2006-02-16</c:pubDate>
		<c:genre>History</c:genre>
		<c:genre>Art</c:genre>
		<c:info>
			<c:book>
				<c:author>Penelope Davies</c:author>
			</c:book>
		</c:info>
	</c:content>
	<c:content category="Fiction">
		<c:title>Cavalcade</c:title>
		<c:pubDate>1933-04-15</c:pubDate>
		<c:genre>Drama</c:genre>
		<c:info>
			<c:film>
				<c:director>Frank LLoyd</c:director>
			</c:film>
		</c:info>
	</c:content>
	<c:content category="Fiction">
		<c:title>War of the Worlds</c:title>
		<c:pubDate>1938-10-30</c:pubDate>
		<c:genre>Science Fiction</c:genre>
		<c:info>
			<c:radio>
				<c:director>Orson Welles</c:director>
			</c:radio>
		</c:info>
	</c:content>
	<c:content category="Fiction">
		<c:title>The Illuminatus! Trilogy</c:title>
		<c:pubDate>1983-12-01</c:pubDate>
		<c:genre>Fantasy</c:genre>
		<c:genre>Drama</c:genre>
		<c:info>
			<c:book>
				<c:author>Robert Shea</c:author>
				<c:author>Robert Anton Wilson</c:author>
			</c:book>
		</c:info>
	</c:content>
</c:catalog>
